import extendGet from "../../../components/extendMethod/get.js";

export default {
	pool_f: "武将卡池一",
	pool_f_info: "抽取 f 阶武将，十连必出新武将",
	pool_d: "武将卡池二",
	pool_d_info: "抽取 d 阶武将，十连必出新武将",
	pool_c: "武将卡池三",
	pool_c_info: "抽取 c 阶武将，十连必出新武将",
	pool_b: "武将卡池四",
	pool_b_info: "抽取 b 阶武将，十连必出新武将",
	pool_a: "武将卡池五",
	pool_a_info: "抽取 a 阶武将，十连必出新武将",
	pool_s: "武将卡池六",
	pool_s_info: "抽取 s 阶武将，十连必出新武将",
	pool_ss: "武将卡池七",
	pool_ss_info: "抽取 ss 阶武将，十连必出新武将",
	pool_sss: "武将卡池八",
	pool_sss_info: "抽取 sss 阶武将，十连必出新武将",

	memoryZhu: "忆铢",
	dreamDian: "梦钿",
	jiangFu: "将符",

	jujubeCake: "枣糕",
	jujubeCake_info: "传统枣糕，枣泥入料，糕体松软，枣香浓郁，天然清甜，暖心又养胃。",
	jujubeCake_effect: "枣糕",
	jujubeCake_effect_info: "每回合开始时，你摸一张牌。",
	pineNutCandy: "松子糖",
	pineNutCandy_info: "苏式松子糖，采芝斋招牌。琥珀糖体裹饱满松仁，入口脆甜，松子清香浓郁，甜而不腻，配茶绝佳。",
	pineNutCandy_effect: "松子糖",
	pineNutCandy_effect_info: "每回合结束时，你摸一张牌。",
	spicyStrips: "辣条",
	spicyStrips_info: "辣条是无数人刻在记忆里的童年味道，香辣够味、嚼劲十足，一口下去满是怀旧。以小麦粉为主料，搭配辣椒、花椒等调味，油润鲜香，辣中带香，越嚼越上头。课间、放学、追剧必备，便宜又解馋，是陪伴几代人长大的经典零食，一口就能找回小时候的快乐时光。",
	spicyStrips_effect: "辣条",
	spicyStrips_effect_info: "每回合结束，你对一名随机敌人造成一点火焰伤害。",
	driedPersimmon: "柿饼",
	driedPersimmon_info: "柿饼是以柿子为原料，经过晾晒或烘干制成的传统甜点。它具有独特的甜味和柔软的口感，富含维生素和纤维，是秋冬季节的美味佳品。",
	driedPersimmon_effect: "柿饼",
	driedPersimmon_effect_info: "每回合结束时，你回复一点体力。",
	greenTongue: "绿舌头",
	greenTongue_info: "“绿舌头”是和路雪于1998年推出的麦酷狮系列组合型冰棍。该产品以果冻为主体，冷冻时口感硬实，温度升高后会变软成果冻质地且可弯曲，形似舌头。",
	greenTongue_effect: "绿舌头",
	greenTongue_effect_info: "每回合开始时，你回复一点体力。",
	whiteRabbitCandy: "大白兔奶糖",
	whiteRabbitCandy_info: "大白兔奶糖是位于中国大陆上海冠生园出品的奶类糖果，1959年开始发售以来深受各地人民欢迎。商标是一只跳跃状的白兔，形象深入民心。大白兔奶糖是白色、有嚼劲的圆柱形奶糖，质感类似西方的鸟结糖，长约3厘米、直径约1厘米，每颗用可吃的米纸包着，再用包装纸包好。",
	whiteRabbitCandy_effect: "大白兔奶糖",
	whiteRabbitCandy_effect_info: "你每次回复体力后摸两张牌。",
	popRocks: "跳跳糖",
	popRocks_info: "跳跳糖亦称爆炸糖，是一种具有娱乐性质的含压缩二氧化碳的休闲食品，其特点是糖粒在口腔内遇热后因二氧化碳汽化产生蹦跳现象。",
	popRocks_effect: "跳跳糖",
	popRocks_effect_info: "你计算与其他角色的距离时-2。",
	maltesers: "麦丽素",
	maltesers_info: "麦丽素是一种巧克力糖果，核心为麦芽糊精，外层包裹巧克力。麦丽素口感酥脆，甜而不腻，深受各年龄层喜爱。它的独特口感和美味使其成为全球畅销的零食之一。",
	maltesers_effect: "麦丽素",
	maltesers_effect_info: "每回合你首次受到的伤害-1。",
	skittles: "彩虹糖",
	skittles_info: "彩虹糖是一款以色彩缤纷、酸甜爽口为特色的经典糖果，凭借亮眼的颜值和活泼的口感，成为无数人的童年记忆。",
	skittles_effect: "彩虹糖",
	skittles_effect_info: "每回合结束时，你可以选择任意两种花色，然后从牌堆获得各一张牌。",
	marshmallow: "棉花糖",
	marshmallow_info: "棉花糖是一种以糖为主要原料，经过加热融化后迅速冷却形成的甜点。它具有轻盈、柔软的质地和甜美的口感，常被用作零食、装饰或制作甜点的配料。",
	marshmallow_effect: "棉花糖",
	marshmallow_effect_info: "每回合开始时，你获得一点护甲。",
	pudding: "小布丁",
	pudding_info: "小布丁是伊利、蒙牛等品牌推出的经典奶油味雪糕，自1999年推出后成为90后群体的“童年之光” 。其奶香浓郁的口感和亲民价格（初期售价0.5元/支）形成核心竞争力，截至2026年仍保持1元/支的平价定位，常被批量采购作为家庭甜点。",
	pudding_effect: "小布丁",
	pudding_effect_info: "你的回合开始，对所有敌人造成一点冰属性伤害。",
	hawthornSlice: "山楂片",
	hawthornSlice_info: "山楂片是以山楂为原料制成的传统零食，具有酸甜可口的味道和丰富的营养价值。它富含维生素C和纤维，有助于消化和增强免疫力，是许多人喜爱的健康零食选择。",
	hawthornSlice_effect: "山楂片",
	hawthornSlice_effect_info: "每回合结束时，你可以选择回复一点体力或摸两张牌。",
	whistleCandy: "口哨糖",
	whistleCandy_info: "口哨糖是一种具有独特设计的糖果，通常呈现为一个小口哨形状。它不仅可以食用，还能发出声音，深受儿童喜爱。口哨糖的甜味和趣味性使其成为派对和节日庆典的热门选择。",
	whistleCandy_effect: "口哨糖",
	whistleCandy_effect_info: "你对非邻位角色造成的伤害翻三倍。",
	AdCalciumMilk: "AD钙奶",
	AdCalciumMilk_info: "AD钙奶是杭州娃哈哈集团有限公司旗下的饮品，有原味等多种口味。",
	AdCalciumMilk_effect: "AD钙奶",
	AdCalciumMilk_effect_info: "每回合结束时，你摸两张牌。",

	p_hp: "体力",
	p_hp_info: "永久增益，放置背包中即生效。",
	p_hp_effect: "体力",
	p_hp_effect_info: "永久增益：游戏开始时，你增加X点体力上限（X为该增益的数量）。",
	p_drawCount: "摸牌数",
	p_drawCount_info: "永久增益，放置背包中即生效。",
	p_drawCount_effect: "摸牌数",
	p_drawCount_effect_info: "永久增益：摸牌阶段摸牌数+X（X为该增益的数量）。",
	p_armor: "护甲",
	p_armor_info: "永久增益，放置背包中即生效。",
	p_armor_effect: "护甲",
	p_armor_effect_info: "永久增益：游戏开始时，你获得X点护甲（X为该增益的数量）。",
	p_distance_subtraction: "距离-",
	p_distance_subtraction_info: "永久增益，放置背包中即生效。",
	p_distance_subtraction_effect: "距离-",
	p_distance_subtraction_effect_info: "永久增益：你计算与其他角色的距离时-X（X为该增益的数量）。",
	p_distance_addition: "距离+",
	p_distance_addition_info: "永久增益，放置背包中即生效。",
	p_distance_addition_effect: "距离+",
	p_distance_addition_effect_info: "永久增益：你计算与其他角色的距离时+X（X为该增益的数量）。",
	p_damage: "伤害",
	p_damage_info: "永久增益，放置背包中即生效。",
	p_damage_effect: "伤害",
	p_damage_effect_info: "永久增益：你造成伤害时+X（X为该增益的数量）。",
	p_skill: "技能",
	p_skill_info: "永久增益，放置背包中即生效。",
	p_skill_effect: "技能",
	p_skill_effect_info: "永久增益：游戏开始你随机获得X个技能（X为该增益的数量）。",
	p_revive: "复活",
	p_revive_info: "永久增益，放置背包中即生效。",
	p_revive_effect: "复活",
	p_revive_effect_info: `永久增益：每局游戏，你有X次${extendGet.easyPoptip("p_revive_effect2", "复活", "本复活指的是免疫本次死亡，然后将体力值恢复至3", "red")}机会（X为该增益的数量）。`,
};
